apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:TzN6upZgDSvpYC5ZjHkVUAS0vDdcE8Q=,iv:cfa/SHh7x5or+rSbuvTJ8+s8/9+RuOuFCrfUiSwTSmY=,tag:SZq7PEVfNiVN2I4XHBO5hg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVzU4TzJITTdFQWhDUXEw
            blpuQjlQRG5kejlXbUJvZWYrdUxvSXVLVEFzCnhuNHRoaWZHbmNUdDdyOWxZUnl2
            TXFIVjIzYlorNTVGUWxYY21uYTNmM1UKLS0tIHl2aWpyNUFGNnM5eVh5aVRISHpL
            QTN3ZEtSQ00zYlVNMStsV2svdk5xVzgK0BTnnfXBNLxMc3Bk18StozGAi9Izp8vY
            4Tsbf49l4Pu7WixG/ZpDgLzVlJ4hVtf2E1Cg79/2gOr2Xs4hDU9mWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13gawzu9xnrjr0auwewlydclkgxvv6um4fz2jrv04l7y3sssf6y2qxx2g6r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T01:11:18Z"
    mac: ENC[AES256_GCM,data:yMj8nnlrptz/ZKfsNZuTUHhW/3N/kxfYEGR4C0ZNnrYTscO6BhAmxR4ncWFAUQTukOfM0h4MH+30O6DeTCEfTjSkrLglUynQaBAu+vXcWtaDScV5qSlb/5Kt31VmHCKOZA6ccEnmLisaAj8H6R09jCgg9zC0SDc76uZzGTHppdg=,iv:QJUnUw3Oc1XuC2xS04hnDtx1zr/VmgStVNLG57Kiqdc=,tag:HA3iJa5ZgSdUnm4GdS8XIA==,type:str]
    version: 3.13.1
