apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:ThEEt51i1ZrkiERPbE4Y2IzG1zwC,iv:pjOT6c8MAlwVI7Wrhc5XQKkfImlITlKfR+7HqkfOUqs=,tag:CdI3EbCmGjxdDVltdHSKLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqL1RHaEZlTG1NVi8zZFRC
            WXFBcnA3U29vZjhRRDllay9rYlE1dnhia2xZCnpWczBMRExGNGljc2hjcGVqck42
            YlN4clI5WkRRa0N2cTFtZlhUYkhQamsKLS0tIG9OdEE3Wm1wK2tYWFZhaVRqSFM0
            Zy9RL1BIU09RcktDdGxYajQ3YkJvUGcKh7lmxjByP2baBTu1I9G0AO32puB5H6Dt
            xa5lOUzgMeNdLrkxT7P1AKV8uL/RwvJPENCP4pOOw7m5gnk94u5/IA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13gawzu9xnrjr0auwewlydclkgxvv6um4fz2jrv04l7y3sssf6y2qxx2g6r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T02:27:28Z"
    mac: ENC[AES256_GCM,data:ECCeyWKxnFH0jDIezMrmObnCElocWzvw4Y0w9pzrNBu1YwdA4gTezcGWhlaCTbCRBUkYRSVcuclNkZeE1ZtabQEwJdWdeUILNc6wb9jQX0/BVzRISPGeLD7xk5fMaHPbsJorNYkWpWpPFuGt5wE5m5o1Os0gkimgx9ltHjj0W2E=,iv:h7KmOXgd1hBYy9cTF0WNqrQgW7VzquSs9rzgx4UjGho=,tag:HWfzsZBy25lwV7dmnGSBFw==,type:str]
    version: 3.13.1
